version: 2
jobs:
  build:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - run: sudo apt install -y git libfreetype6-dev libjpeg62-turbo-dev
      - run: sudo docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
      - run: sudo docker-php-ext-install -j$(nproc) gd
      - run: sudo composer self-update
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          - v1-dependencies-
      - run: composer install -n --prefer-dist
      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: ./vendor/bin/phpunit --configuration phpunit.xml
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
