name: CI

on: [push, pull_request]

jobs:
  test:
    name: PHP Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - name: Setup PHP
      uses: shivammathur/setup-php@1.1.1
      with:
        php-version: 7.1
    - run: composer install
    - run: vendor/bin/phpunit
      env:
        MOCK_URL: ${{ secrets.MockServer }}
